'use client';
import {useRef,useState} from 'react';
import {Move,RotateCw,Scaling,Maximize2,Download,Grid2X2,MousePointer2} from 'lucide-react';
import {clone,type ModelObject,type V2} from '@/lib/morph/model';
import {svgUV} from '@/lib/morph/files';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export default function UVEditor({object,onChange}:{object?:ModelObject;onChange:(o:ModelObject,label:string)=>void}){const [sel,setSel]=useState<number[]>([]),[verts,setVerts]=useState<string[]>([]),[mode,setMode]=useState('island'),[action,setAction]=useState('move'),[zoom,setZoom]=useState(1),svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;uvs:V2[][];sel:number[];verts:string[]}|null>(null),[preview,setPreview]=useState<V2[][]|null>(null),key=useRef(object?.id);if(key.current!==object?.id){key.current=object?.id;setSel([]);setVerts([]);setPreview(null);}const uvs=preview??object?.mesh.uvs??[];
 const coords=(e:React.PointerEvent)=>{const r=svg.current!.getBoundingClientRect(),scale=Math.min(r.width,r.height)/600;return{x:e.clientX/scale,y:e.clientY/scale};};
 function start(e:React.PointerEvent,fi:number,vi?:number){e.stopPropagation();if(!object)return;let ids=sel,vs=verts;if(mode==='island'){ids=e.shiftKey?sel.includes(fi)?sel.filter(i=>i!==fi):[...sel,fi]:sel.includes(fi)?sel:[fi];setSel(ids);}else{const k=`${fi}:${vi}`;vs=e.shiftKey?verts.includes(k)?verts.filter(s=>s!==k):[...verts,k]:verts.includes(k)?verts:[k];setVerts(vs);}drag.current={...coords(e),uvs:clone(object.mesh.uvs),sel:ids,verts:vs};svg.current!.setPointerCapture(e.pointerId);}
 function move(e:React.PointerEvent){const d=drag.current;if(!d)return;const p=coords(e),dx=(p.x-d.x)/(480*zoom),dy=-(p.y-d.y)/(480*zoom),next=clone(d.uvs),selected=(f:number,v:number)=>mode==='island'?d.sel.includes(f):d.verts.includes(`${f}:${v}`),points=next.flatMap((f,i)=>f.filter((_,j)=>selected(i,j)));if(!points.length)return;const cx=points.reduce((s,p)=>s+p[0],0)/points.length,cy=points.reduce((s,p)=>s+p[1],0)/points.length;next.forEach((f,i)=>f.forEach((uv,j)=>{if(!selected(i,j))return;const x=uv[0]-cx,y=uv[1]-cy;if(action==='move'){uv[0]+=dx;uv[1]+=dy;}if(action==='scale'){const scale=Math.max(.05,1+dx*2);uv[0]=cx+x*scale;uv[1]=cy+y*scale;}if(action==='rotate'){const a=dx*Math.PI*2;uv[0]=cx+x*Math.cos(a)-y*Math.sin(a);uv[1]=cy+x*Math.sin(a)+y*Math.cos(a);}}));setPreview(next);}
 function end(){if(drag.current&&preview&&object){const o=clone(object);o.mesh.uvs=preview;onChange(o,'Transform UVs');}drag.current=null;setPreview(null);}
 function selectAll(){setSel(uvs.map((_,i)=>i));setVerts(uvs.flatMap((f,i)=>f.map((_,j)=>`${i}:${j}`)));}
 return <section className="uv-workspace"><div className="panel-title"><span><Grid2X2 size={15}/> UV EDITOR</span><button className="icon-button" title="Export UV layout as SVG" aria-label="Export UV layout" disabled={!object} onClick={()=>object&&svgUV(object)}><Download size={15}/></button></div><div className="uv-tools"><Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="island">Faces</TabsTrigger><TabsTrigger value="vertex">Vertices</TabsTrigger></TabsList></Tabs><span className="grow"/>{[{id:'move',icon:Move},{id:'rotate',icon:RotateCw},{id:'scale',icon:Scaling}].map(({id,icon:Icon})=><button key={id} className={'icon-button '+(action===id?'active':'')} title={'UV '+id} aria-label={'UV '+id} onClick={()=>setAction(id)}><Icon size={16}/></button>)}</div><div className="uv-canvas" tabIndex={0} onKeyDown={e=>{if(e.key.toLowerCase()==='a'){e.preventDefault();e.stopPropagation();selectAll();}}}><svg ref={svg} viewBox="0 0 600 600" onPointerMove={move} onPointerUp={end} onPointerCancel={end} onPointerDown={()=>{setSel([]);setVerts([]);}} aria-label="Editable UV coordinate canvas"><defs><pattern id="uvchecker" width="60" height="60" patternUnits="userSpaceOnUse"><rect width="60" height="60" fill="#23262b"/><path d="M0 0H30V30H0ZM30 30H60V60H30Z" fill="#2a2d32"/></pattern></defs><g transform={`translate(${300-240*zoom},${300-240*zoom}) scale(${zoom})`}><rect width="480" height="480" fill="url(#uvchecker)" stroke="#6d6b61"/>{object?.material.texture&&<image href={object.material.texture} width="480" height="480" opacity=".55"/>}{Array.from({length:9},(_,i)=><g key={i} stroke="#4c4e53" strokeWidth=".5"><line x1={i*60} x2={i*60} y1={0} y2={480}/><line x1={0} x2={480} y1={i*60} y2={i*60}/></g>)}{uvs.map((f,i)=><g key={i}><polygon points={f.map(p=>`${p[0]*480},${(1-p[1])*480}`).join(' ')} fill={sel.includes(i)?'#d5ad6330':'#00000005'} stroke={sel.includes(i)?'#e2b869':'#96918a'} strokeWidth={sel.includes(i)?2:1} onPointerDown={e=>mode==='island'&&start(e,i)}/>{mode==='vertex'&&f.map((p,j)=><circle key={j} cx={p[0]*480} cy={(1-p[1])*480} r={verts.includes(`${i}:${j}`)?4:3} fill={verts.includes(`${i}:${j}`)?'#ffd080':'#96918a'} onPointerDown={e=>start(e,i,j)}/>)}</g>)}<text x="0" y="502" fill="#a3a4a8" fontSize="13">0, 0</text><text x="457" y="502" fill="#a3a4a8" fontSize="13">1, 0</text><text x="0" y="-12" fill="#a3a4a8" fontSize="13">0, 1</text></g></svg>{!object&&<div className="viewport-empty">Select a mesh to edit its UVs</div>}</div><div className="uv-footer"><button onClick={selectAll}><MousePointer2 size={13}/>Select all</button><span>{mode==='island'?sel.length+' faces':verts.length+' corners'}</span><button onClick={()=>setZoom(z=>z===1?1.5:1)}><Maximize2 size={13}/>{zoom===1?'100%':'150%'}</button></div><p className="uv-hint">Select and drag to {action}. Shift-click to add. <kbd>A</kbd> selects all.</p></section>;
}
