import * as THREE from 'three';
export type V3=[number,number,number];
export type V2=[number,number];
export type MeshData={vertices:V3[];faces:number[][];uvs:V2[][]};
export type MaterialData={name:string;color:string;metalness:number;roughness:number;opacity:number;emissive:string;texture?:string;normalMap?:string;roughnessMap?:string;checker?:boolean;repeat:number};
export type ModelObject={id:string;name:string;mesh:MeshData;position:V3;rotation:V3;scale:V3;material:MaterialData;visible:boolean;smooth:boolean};
export type Project={format:'morph-modeling';version:1;name:string;objects:ModelObject[]};
export type ElementMode='vertex'|'edge'|'face';
export const uid=()=>globalThis.crypto?.randomUUID?.()??Math.random().toString(36).slice(2);
export const clone=<T,>(v:T):T=>structuredClone(v);
export const vec=(p:V3)=>new THREE.Vector3(...p);
export const arr=(p:THREE.Vector3)=>p.toArray() as V3;
export const materialPresets:MaterialData[]=[
{name:'Morph gold',color:'#c49a4b',metalness:.78,roughness:.26,opacity:1,emissive:'#000000',repeat:1},
{name:'Crimson',color:'#b92732',metalness:.32,roughness:.3,opacity:1,emissive:'#000000',repeat:1},
{name:'Obsidian',color:'#25272d',metalness:.6,roughness:.29,opacity:1,emissive:'#000000',repeat:1},
{name:'Porcelain',color:'#e9e5da',metalness:.08,roughness:.24,opacity:1,emissive:'#000000',repeat:1},
{name:'Brushed alloy',color:'#8995a1',metalness:.92,roughness:.43,opacity:1,emissive:'#000000',repeat:1},
{name:'Clay',color:'#89857e',metalness:0,roughness:.85,opacity:1,emissive:'#000000',repeat:1},
];
export function normal(m:MeshData,f:number[]){const n=new THREE.Vector3();for(let i=0;i<f.length;i++){const a=m.vertices[f[i]],b=m.vertices[f[(i+1)%f.length]];n.x+=(a[1]-b[1])*(a[2]+b[2]);n.y+=(a[2]-b[2])*(a[0]+b[0]);n.z+=(a[0]-b[0])*(a[1]+b[1]);}return n.normalize();}
export function faceCenter(m:MeshData,f:number[]){return f.reduce((s,i)=>s.add(vec(m.vertices[i])),new THREE.Vector3()).divideScalar(f.length);}
export function projectUV(m:MeshData,kind:'box'|'planar'|'cylinder'|'face'='box'):MeshData{
 const b=new THREE.Box3().setFromPoints(m.vertices.map(vec));const size=b.getSize(new THREE.Vector3());const norm=(p:number,a:number)=>(p-b.min.getComponent(a))/Math.max(size.getComponent(a),.0001);
 m.uvs=m.faces.map(f=>{const n=normal(m,f);const axis=kind==='planar'?1:Math.abs(n.x)>Math.abs(n.y)&&Math.abs(n.x)>Math.abs(n.z)?0:Math.abs(n.y)>Math.abs(n.z)?1:2;
 if(kind==='face'){const origin=vec(m.vertices[f[0]]),u=vec(m.vertices[f[1]]).sub(origin).normalize(),v=new THREE.Vector3().crossVectors(n,u);const coords=f.map(i=>{const p=vec(m.vertices[i]).sub(origin);return [p.dot(u),p.dot(v)] as V2});const xs=coords.map(p=>p[0]),ys=coords.map(p=>p[1]),a=Math.min(...xs),c=Math.min(...ys),s=Math.max(Math.max(...xs)-a,Math.max(...ys)-c,.001);return coords.map(p=>[(p[0]-a)/s,(p[1]-c)/s] as V2);}
 return f.map(i=>{const p=m.vertices[i];if(kind==='cylinder')return [Math.atan2(p[2],p[0])/(Math.PI*2)+.5,norm(p[1],1)] as V2;return axis===0?[norm(p[2],2),norm(p[1],1)]:axis===1?[norm(p[0],0),norm(p[2],2)]:[norm(p[0],0),norm(p[1],1)] as V2;});});
 if(kind==='cylinder')m.uvs.forEach(f=>{if(Math.max(...f.map(p=>p[0]))-Math.min(...f.map(p=>p[0]))>.5)f.forEach(p=>{if(p[0]<.5)p[0]+=1;});});return m;
}
export function packUV(m:MeshData,padding=.04){const n=Math.ceil(Math.sqrt(m.faces.length));m.uvs=m.uvs.map((f,i)=>{const minX=Math.min(...f.map(p=>p[0])),minY=Math.min(...f.map(p=>p[1]));const s=Math.max(Math.max(...f.map(p=>p[0]))-minX,Math.max(...f.map(p=>p[1]))-minY,.0001);return f.map(p=>[((i%n)+padding+(p[0]-minX)/s*(1-padding*2))/n,(Math.floor(i/n)+padding+(p[1]-minY)/s*(1-padding*2))/n] as V2);});return m;}
export function primitive(kind:string):MeshData{const vertices:V3[]=[],faces:number[][]=[];const add=(x:number,y:number,z:number)=>(vertices.push([x,y,z]),vertices.length-1);
 if(kind==='Cube'){vertices.push([-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]);faces.push([0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[0,1,5,4],[3,7,6,2]);}
 else if(kind==='Plane'){vertices.push([-1,0,-1],[-1,0,1],[1,0,1],[1,0,-1]);faces.push([0,1,2,3]);}
 else if(kind==='Cylinder'||kind==='Cone'){const n=32;for(let y=0;y<2;y++)for(let i=0;i<n;i++){const a=i/n*Math.PI*2;add(Math.cos(a)*(kind==='Cone'&&y===1?0:1),y*2-1,Math.sin(a)*(kind==='Cone'&&y===1?0:1));}for(let i=0;i<n;i++)faces.push([i,i+n,(i+1)%n+n,(i+1)%n]);faces.push(Array.from({length:n},(_,i)=>i));if(kind==='Cylinder')faces.push(Array.from({length:n},(_,i)=>n*2-1-i));}
 else if(kind==='Torus'){const n=48,s=16;for(let i=0;i<n;i++)for(let j=0;j<s;j++){const a=i/n*Math.PI*2,b=j/s*Math.PI*2;add((1+Math.cos(b)*.32)*Math.cos(a),Math.sin(b)*.32,(1+Math.cos(b)*.32)*Math.sin(a));}for(let i=0;i<n;i++)for(let j=0;j<s;j++)faces.push([i*s+j,i*s+(j+1)%s,((i+1)%n)*s+(j+1)%s,((i+1)%n)*s+j]);}
 else if(kind==='Sphere'){const n=32,s=16;for(let j=0;j<=s;j++)for(let i=0;i<n;i++){const a=i/n*Math.PI*2,b=j/s*Math.PI;add(Math.sin(b)*Math.cos(a),Math.cos(b),Math.sin(b)*Math.sin(a));}for(let j=0;j<s;j++)for(let i=0;i<n;i++)faces.push([j*n+i,j*n+(i+1)%n,(j+1)*n+(i+1)%n,(j+1)*n+i]);}
 else return fromGeometry(new THREE.IcosahedronGeometry(1,1));const m=projectUV({vertices,faces,uvs:[]});if(kind==='Sphere'||kind==='Cone')weld(m,.000001);return m;
}
export function object(kind='Cube',mat=materialPresets[0]):ModelObject{return {id:uid(),name:kind,mesh:primitive(kind),position:[0,1,0],rotation:[0,0,0],scale:[1,1,1],material:clone(mat),visible:true,smooth:['Sphere','Torus','Cylinder','Cone'].includes(kind)};}
export function starterProject():Project{const a=object('Cube');a.name='Chamfer cube';a.mesh=bevel(a.mesh,.15);a.position=[-.95,1.02,.1];a.rotation=[0,-18,0];a.scale=[.88,.88,.88];const b=object('Torus',materialPresets[1]);b.position=[1.35,1.35,-.65];b.rotation=[68,12,-22];const c=object('Sphere',materialPresets[2]);c.position=[1.6,.56,1.25];c.scale=[.56,.56,.56];return{format:'morph-modeling',version:1,name:'Form study',objects:[a,b,c]};}
export function matrix(o:ModelObject){return new THREE.Matrix4().compose(vec(o.position),new THREE.Quaternion().setFromEuler(new THREE.Euler(...o.rotation.map(n=>THREE.MathUtils.degToRad(n)) as V3)),vec(o.scale));}
export function applyMatrix(m:MeshData,t:THREE.Matrix4){m.vertices=m.vertices.map(v=>arr(vec(v).applyMatrix4(t)));if(t.determinant()<0){m.faces.forEach(f=>f.reverse());m.uvs.forEach(f=>f.reverse());}return m;}
export function edges(m:MeshData){const seen=new Map<string,[number,number]>();m.faces.forEach(f=>f.forEach((a,j)=>{const b=f[(j+1)%f.length];seen.set([a,b].sort((x,y)=>x-y).join(':'),[Math.min(a,b),Math.max(a,b)]);}));return [...seen.values()];}
export function selectedVertices(m:MeshData,mode:ElementMode,selection:number[]){if(mode==='vertex')return selection;const list=mode==='edge'?edges(m):m.faces;return [...new Set(selection.flatMap(i=>list[i]??[]))];}
export function selectedFaces(m:MeshData,mode:ElementMode,selection:number[]){if(mode==='face')return selection;const ids=new Set(selectedVertices(m,mode,selection));return m.faces.flatMap((f,i)=>f.every(v=>ids.has(v))?[i]:[]);}
export function extrude(m:MeshData,selection:number[],distance=.35){if(!selection.length)throw new Error('Select one or more faces to extrude.');if(Math.abs(distance)<.000001)throw new Error('Extrusion distance must be nonzero.');const set=new Set(selection),vs=[...new Set(selection.flatMap(i=>m.faces[i]))],ns=new Map<number,THREE.Vector3>();selection.forEach(i=>{const n=normal(m,m.faces[i]);m.faces[i].forEach(v=>ns.set(v,(ns.get(v)??new THREE.Vector3()).add(n)));});const remap=new Map<number,number>();vs.forEach(v=>{remap.set(v,m.vertices.length);m.vertices.push(arr(vec(m.vertices[v]).addScaledVector(ns.get(v)!.normalize(),distance)));});const boundary=new Map<string,{a:number;b:number;count:number}>();selection.forEach(i=>m.faces[i].forEach((a,j,f)=>{const b=f[(j+1)%f.length],key=[a,b].sort((x,y)=>x-y).join(':');const old=boundary.get(key);boundary.set(key,{a,b,count:(old?.count??0)+1});}));const newFaces:number[][]=[],newUV:V2[][]=[],result:number[]=[];m.faces.forEach((f,i)=>{if(!set.has(i)){newFaces.push(f);newUV.push(m.uvs[i]);}else{result.push(newFaces.length);newFaces.push(f.map(v=>remap.get(v)!));newUV.push(m.uvs[i]);}});boundary.forEach(({a,b,count})=>{if(count===1){newFaces.push([a,b,remap.get(b)!,remap.get(a)!]);newUV.push([[0,0],[1,0],[1,Math.abs(distance)],[0,Math.abs(distance)]]);}});m.faces=newFaces;m.uvs=newUV;return result;}
export function inset(m:MeshData,selection:number[],amount=.15){if(!selection.length)throw new Error('Select one or more faces to inset.');amount=Math.min(.9,Math.max(.001,amount));const set=new Set(selection),fs:number[][]=[],uvs:V2[][]=[],result:number[]=[];m.faces.forEach((f,i)=>{if(!set.has(i)){fs.push(f);uvs.push(m.uvs[i]);return;}const center=faceCenter(m,f),uv=m.uvs[i],uc:V2=[uv.reduce((s,p)=>s+p[0],0)/uv.length,uv.reduce((s,p)=>s+p[1],0)/uv.length];const inner=f.map(v=>{m.vertices.push(arr(vec(m.vertices[v]).lerp(center,amount)));return m.vertices.length-1;});const iu=uv.map(p=>[p[0]+(uc[0]-p[0])*amount,p[1]+(uc[1]-p[1])*amount] as V2);result.push(fs.length);fs.push(inner);uvs.push(iu);f.forEach((v,j)=>{const k=(j+1)%f.length;fs.push([v,f[k],inner[k],inner[j]]);uvs.push([uv[j],uv[k],iu[k],iu[j]]);});});m.faces=fs;m.uvs=uvs;return result;}
export function subdivide(m:MeshData){if(m.faces.length>25000)throw new Error('Subdivision limit reached (25,000 source faces).');const midpoint=new Map<string,number>(),result:number[][]=[],uvs:V2[][]=[];m.faces.forEach((f,fi)=>{const c=m.vertices.length;m.vertices.push(arr(faceCenter(m,f)));const uv=m.uvs[fi],uc:V2=[uv.reduce((s,p)=>s+p[0],0)/f.length,uv.reduce((s,p)=>s+p[1],0)/f.length];const mids=f.map((a,i)=>{const b=f[(i+1)%f.length],key=[a,b].sort((a,b)=>a-b).join(':');if(!midpoint.has(key)){midpoint.set(key,m.vertices.length);m.vertices.push(arr(vec(m.vertices[a]).add(vec(m.vertices[b])).multiplyScalar(.5)));}return midpoint.get(key)!;});f.forEach((a,i)=>{const p=(i+f.length-1)%f.length,n=(i+1)%f.length;result.push([a,mids[i],c,mids[p]]);uvs.push([uv[i],[(uv[i][0]+uv[n][0])/2,(uv[i][1]+uv[n][1])/2],uc,[(uv[i][0]+uv[p][0])/2,(uv[i][1]+uv[p][1])/2]]);});});m.faces=result;m.uvs=uvs;return m;}
export function bevel(source:MeshData,amount=.12):MeshData{if(source.faces.length>5000)throw new Error('Bevel is limited to 5,000 faces.');const m:MeshData={vertices:[],faces:[],uvs:[]},corners=new Map<number,{v:number;center:THREE.Vector3}[]>(),edgeMap=new Map<string,{a:number;b:number;na:number;nb:number}[]>();source.faces.forEach(f=>{const c=faceCenter(source,f);const inner=f.map(v=>{const i=m.vertices.length,p=vec(source.vertices[v]).lerp(c,Math.min(.45,Math.max(.001,amount)));m.vertices.push(arr(p));corners.set(v,[...(corners.get(v)??[]),{v:i,center:p}]);return i;});m.faces.push(inner);f.forEach((a,i)=>{const j=(i+1)%f.length,b=f[j],key=[a,b].sort((a,b)=>a-b).join(':');edgeMap.set(key,[...(edgeMap.get(key)??[]),{a,b,na:inner[i],nb:inner[j]}]);});});edgeMap.forEach(es=>{if(es.length===2){const [a,b]=es;m.faces.push([a.nb,a.na,b.nb,b.na]);}});corners.forEach((cs,original)=>{if(cs.length<3)return;const n=cs.reduce((s,p)=>s.add(p.center.clone().sub(vec(source.vertices[original]))),new THREE.Vector3()).normalize().negate(),c=cs.reduce((s,p)=>s.add(p.center),new THREE.Vector3()).divideScalar(cs.length),u=cs[0].center.clone().sub(c).normalize(),v=new THREE.Vector3().crossVectors(n,u);cs.sort((a,b)=>Math.atan2(a.center.clone().sub(c).dot(v),a.center.clone().sub(c).dot(u))-Math.atan2(b.center.clone().sub(c).dot(v),b.center.clone().sub(c).dot(u)));m.faces.push(cs.map(p=>p.v));});return projectUV(m);}
export function weld(m:MeshData,tolerance=.001){const map=new Map<string,number>(),remap:number[]=[],verts:V3[]=[];m.vertices.forEach(v=>{const key=v.map(n=>Math.round(n/tolerance)).join(':');if(!map.has(key)){map.set(key,verts.length);verts.push(v);}remap.push(map.get(key)!);});const fs:number[][]=[],uvs:V2[][]=[];m.faces.forEach((f,i)=>{const used=new Set<number>(),nf:number[]=[],nu:V2[]=[];f.forEach((v,j)=>{const r=remap[v];if(!used.has(r)){used.add(r);nf.push(r);nu.push(m.uvs[i][j]);}});if(nf.length>=3){fs.push(nf);uvs.push(nu);}});m.vertices=verts;m.faces=fs;m.uvs=uvs;return m;}
export function deleteFaces(m:MeshData,selection:number[]){const set=new Set(selection);m.faces=m.faces.filter((_,i)=>!set.has(i));m.uvs=m.uvs.filter((_,i)=>!set.has(i));return compact(m);}
export function compact(m:MeshData){const used=[...new Set(m.faces.flat())],map=new Map(used.map((v,i)=>[v,i]));m.vertices=used.map(i=>m.vertices[i]);m.faces=m.faces.map(f=>f.map(v=>map.get(v)!));return m;}
export function triangles(m:MeshData,f:number[]){if(f.length===3)return [[0,1,2]];const n=normal(m,f),a=Math.abs(n.x)>Math.abs(n.y)&&Math.abs(n.x)>Math.abs(n.z)?0:Math.abs(n.y)>Math.abs(n.z)?1:2;const p=f.map(i=>{const v=m.vertices[i];return new THREE.Vector2(v[(a+1)%3],v[(a+2)%3]);}),ts=THREE.ShapeUtils.triangulateShape(p,[]),result=ts.length?ts:Array.from({length:f.length-2},(_,j)=>[0,j+1,j+2]);return result.map(t=>{const a=vec(m.vertices[f[t[0]]]),b=vec(m.vertices[f[t[1]]]),c=vec(m.vertices[f[t[2]]]);return b.sub(a).cross(c.sub(a)).dot(n)<0?[t[0],t[2],t[1]]:t;});}
export function triangulate(m:MeshData){const fs:number[][]=[],uvs:V2[][]=[];m.faces.forEach((f,i)=>triangles(m,f).forEach(t=>{fs.push(t.map(j=>f[j]));uvs.push(t.map(j=>m.uvs[i][j]));}));m.faces=fs;m.uvs=uvs;return m;}
export function geometry(m:MeshData,smooth=false){const positions:number[]=[],uvs:number[]=[],normals:number[]=[],faceMap:number[]=[],sums=m.vertices.map(()=>new THREE.Vector3());if(smooth)m.faces.forEach(f=>{const n=normal(m,f);f.forEach(v=>sums[v].add(n));});m.faces.forEach((f,i)=>{const n=normal(m,f);triangles(m,f).forEach(t=>{faceMap.push(i);t.forEach(j=>{positions.push(...m.vertices[f[j]]);uvs.push(...(m.uvs[i]?.[j]??[0,0]));normals.push(...(smooth?sums[f[j]].clone().normalize():n).toArray());});});});const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.userData.faceMap=faceMap;g.computeBoundingSphere();return g;}
export function fromGeometry(g:THREE.BufferGeometry):MeshData{const m:MeshData={vertices:[],faces:[],uvs:[]},p=g.getAttribute('position'),uv=g.getAttribute('uv'),map=new Map<string,number>(),ids:number[]=[];for(let i=0;i<p.count;i++){const v:V3=[p.getX(i),p.getY(i),p.getZ(i)],key=v.map(n=>n.toFixed(6)).join(':');if(!map.has(key)){map.set(key,m.vertices.length);m.vertices.push(v);}ids.push(map.get(key)!);}const ix=g.index;for(let i=0;i<(ix?ix.count:p.count);i+=3){const indices=[0,1,2].map(j=>ix?ix.getX(i+j):i+j),face=indices.map(j=>ids[j]);if(new Set(face).size<3)continue;m.faces.push(face);m.uvs.push(indices.map(j=>uv?[uv.getX(j),uv.getY(j)]:[0,0]));}if(!uv)projectUV(m);return m;}
export function joinObjects(objs:ModelObject[]):ModelObject{const result=object('Cube',objs[0].material);result.name='Joined mesh';result.position=[0,0,0];result.mesh={vertices:[],faces:[],uvs:[]};objs.forEach(o=>{const m=applyMatrix(clone(o.mesh),matrix(o)),offset=result.mesh.vertices.length;result.mesh.vertices.push(...m.vertices);result.mesh.faces.push(...m.faces.map(f=>f.map(v=>v+offset)));result.mesh.uvs.push(...m.uvs);});return result;}
export function validateProject(raw:unknown):Project{const p=raw as Project;if(!p||p.format!=='morph-modeling'||p.version!==1||!Array.isArray(p.objects)||p.objects.length>500)throw new Error('This is not a supported Morph project.');let count=0;const ids=new Set<string>(),triple=(v:unknown,n=3):v is number[]=>Array.isArray(v)&&v.length===n&&v.every(x=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<1e8);for(const o of p.objects){if(!o||typeof o.id!=='string'||ids.has(o.id)||typeof o.name!=='string'||!o.mesh||!Array.isArray(o.mesh.vertices)||!Array.isArray(o.mesh.faces)||!Array.isArray(o.mesh.uvs))throw new Error('Invalid mesh in project.');ids.add(o.id);count+=o.mesh.vertices.length;if(count>250000)throw new Error('Prototype project limit: 250,000 vertices.');if(!o.mesh.vertices.every(v=>triple(v))||!o.mesh.faces.every(f=>Array.isArray(f)&&f.length>=3&&f.length<=4096&&f.every(v=>Number.isInteger(v)&&v>=0&&v<o.mesh.vertices.length)))throw new Error('Invalid geometry.');if(o.mesh.uvs.length!==o.mesh.faces.length||!o.mesh.uvs.every((f,i)=>Array.isArray(f)&&f.length===o.mesh.faces[i].length&&f.every(uv=>triple(uv,2))))throw new Error('Invalid UV coordinates.');if(![o.position,o.rotation,o.scale].every(v=>triple(v)))throw new Error('Invalid transforms.');const m=o.material;if(!m||![m.color,m.emissive].every(c=>typeof c==='string'&&/^#[a-fA-F0-9]{6}$/.test(c))||![m.metalness,m.roughness,m.opacity].every(x=>Number.isFinite(x)&&x>=0&&x<=1)||!Number.isFinite(m.repeat)||m.repeat<=0||m.repeat>100)throw new Error('Invalid material settings.');for(const key of ['texture','normalMap','roughnessMap'] as const)if(m[key]&&!/^data:image\/(png|jpeg|webp);base64,/.test(m[key]!))throw new Error('Textures must be embedded PNG, JPEG or WebP images.');}p.name=typeof p.name==='string'?p.name.slice(0,120):'Untitled';return p;}
export function sliceMesh(m:MeshData,axis:number,position=0){const cache=new Map<string,number>(),fs:number[][]=[],uvs:V2[][]=[];let cuts=0;m.faces.forEach((f,fi)=>{const ds=f.map(v=>m.vertices[v][axis]-position);if(!ds.some(d=>d>1e-7)||!ds.some(d=>d< -1e-7)){fs.push(f);uvs.push(m.uvs[fi]);return;}cuts++;for(const side of [1,-1]){const face:number[]=[],uv:V2[]=[];f.forEach((v,j)=>{const k=(j+1)%f.length,w=f[k],a=ds[j],b=ds[k],u=m.uvs[fi][j],un=m.uvs[fi][k];if(a*side>=-1e-7){face.push(v);uv.push(u);}if((a>1e-7&&b< -1e-7)||(a< -1e-7&&b>1e-7)){const t=a/(a-b),key=[v,w].sort((a,b)=>a-b).join(':');if(!cache.has(key)){cache.set(key,m.vertices.length);m.vertices.push(arr(vec(m.vertices[v]).lerp(vec(m.vertices[w]),t)));}face.push(cache.get(key)!);uv.push([u[0]+(un[0]-u[0])*t,u[1]+(un[1]-u[1])*t]);}});if(face.length>=3){fs.push(face);uvs.push(uv);}}});if(!cuts)throw new Error('The slice plane does not cross this mesh. Adjust its position.');m.faces=fs;m.uvs=uvs;return m;}
export function mergeSelected(m:MeshData,ids:number[]){if(ids.length<2)throw new Error('Select at least two vertices to merge.');const center=ids.reduce((s,i)=>s.add(vec(m.vertices[i])),new THREE.Vector3()).divideScalar(ids.length);ids.forEach(i=>m.vertices[i]=arr(center));return weld(m,.000001);}
export function fillFace(m:MeshData,ids:number[]){if(ids.length<3)throw new Error('Select at least three vertices to fill.');const c=ids.reduce((s,i)=>s.add(vec(m.vertices[i])),new THREE.Vector3()).divideScalar(ids.length),u=vec(m.vertices[ids[0]]).sub(c).normalize();let n=new THREE.Vector3();for(let i=1;i<ids.length;i++){n=new THREE.Vector3().crossVectors(u,vec(m.vertices[ids[i]]).sub(c)).normalize();if(n.length()>.9)break;}if(n.length()<.9)throw new Error('These vertices are collinear.');const v=new THREE.Vector3().crossVectors(n,u),sorted=[...ids].sort((a,b)=>{const p=vec(m.vertices[a]).sub(c),q=vec(m.vertices[b]).sub(c);return Math.atan2(p.dot(v),p.dot(u))-Math.atan2(q.dot(v),q.dot(u));});m.faces.push(sorted);m.uvs.push(projectUV({vertices:m.vertices,faces:[sorted],uvs:[]},'face').uvs[0]);return m;}
