import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {SVGRenderer} from 'three/addons/renderers/SVGRenderer.js';
import {arr,clone,edges,geometry,matrix,selectedVertices,vec,type Project,type ModelObject,type ElementMode,type V3} from './model';
import {checkerTexture} from './files';
export type ViewState={project:Project;selected:string[];mode:'object'|'edit';element:ElementMode;selection:number[];tool:'select'|'translate'|'rotate'|'scale';snap:boolean;space:'world'|'local';shading:'material'|'solid'|'wireframe';grid:boolean;wire:boolean;xray:boolean};
export class Viewport {
 renderer:THREE.WebGLRenderer|SVGRenderer;software=false;dirty=true;scene=new THREE.Scene();camera:THREE.PerspectiveCamera|THREE.OrthographicCamera;controls:OrbitControls;transform:TransformControls;pivot=new THREE.Object3D();group=new THREE.Group();overlay=new THREE.Group();grid:THREE.GridHelper;state:ViewState|null=null;frameId=0;resize:ResizeObserver;meshes=new Map<string,THREE.Mesh>();textures=new Map<string,THREE.Texture>();startMatrix=new THREE.Matrix4();startState:ViewState|null=null;host:HTMLElement;dragStart=[0,0];gizmoUsed=false;onSelect:(id:string|null,element:number|null,add:boolean)=>void;onCommit:(objects:ModelObject[])=>void;onView:(v:string)=>void;
 constructor(host:HTMLElement,onSelect:Viewport['onSelect'],onCommit:Viewport['onCommit'],onView:Viewport['onView']){this.host=host;this.onSelect=onSelect;this.onCommit=onCommit;this.onView=onView;
 try{this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;}catch{this.software=true;const r=new SVGRenderer();r.setQuality('high');r.setPrecision(2);this.renderer=r;}this.renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(this.renderer.domElement);
 this.scene.background=new THREE.Color('#222428');this.scene.fog=new THREE.Fog('#222428',25,70);this.camera=new THREE.PerspectiveCamera(40,host.clientWidth/host.clientHeight,.01,1000);this.camera.position.set(7.5,5.5,8.5);this.controls=new OrbitControls(this.camera,this.renderer.domElement as HTMLElement);this.controls.target.set(.2,.8,0);this.controls.enableDamping=true;this.controls.dampingFactor=.09;this.controls.minDistance=.2;this.controls.maxDistance=150;this.controls.addEventListener('change',()=>this.dirty=true);this.controls.addEventListener('start',()=>this.onView(this.camera instanceof THREE.OrthographicCamera?'Orthographic':'User perspective'));
 if(this.renderer instanceof THREE.WebGLRenderer){const env=new RoomEnvironment(),pmrem=new THREE.PMREMGenerator(this.renderer);this.scene.environment=pmrem.fromScene(env,.04).texture;env.dispose();pmrem.dispose();this.scene.environmentIntensity=.7;}else this.scene.add(new THREE.AmbientLight(0xffffff,.35));this.scene.add(new THREE.HemisphereLight(0xdce4ee,0x302727,2));const key=new THREE.DirectionalLight(0xffecd4,this.software?.7:4);key.position.set(-3,8,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=key.shadow.camera.bottom=-12;key.shadow.camera.right=key.shadow.camera.top=12;key.shadow.normalBias=.03;this.scene.add(key);const rim=new THREE.DirectionalLight(0xe4eeff,this.software?.4:2);rim.position.set(4,3,-5);this.scene.add(rim);
 this.grid=new THREE.GridHelper(100,100,0x505052,0x35373b);if(this.software){const gm=this.grid.material as THREE.LineBasicMaterial;gm.color.set(0x35373b);gm.transparent=true;gm.opacity=.65;}this.grid.position.y=-.015;this.scene.add(this.grid);if(!this.software){const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.ShadowMaterial({opacity:.22}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;floor.receiveShadow=true;this.scene.add(floor);}const axisLine=(a:V3,b:V3,c:number)=>new THREE.Line(new THREE.BufferGeometry().setFromPoints([vec(a),vec(b)]),new THREE.LineBasicMaterial({color:c,transparent:true,opacity:.5}));this.grid.add(axisLine([-50,.001,0],[50,.001,0],0xa44b4b),axisLine([0,.001,-50],[0,.001,50],0x496fa2));
 this.scene.add(this.group,this.overlay,this.pivot);this.transform=new TransformControls(this.camera,this.renderer.domElement as HTMLElement);this.transform.setSize(.75);this.scene.add(this.transform.getHelper());this.transform.addEventListener('change',()=>this.dirty=true);this.transform.addEventListener('dragging-changed',e=>this.controls.enabled=!e.value);this.transform.addEventListener('mouseDown',()=>{this.gizmoUsed=true;this.startState=this.state?clone(this.state):null;this.pivot.updateMatrixWorld();this.startMatrix.copy(this.pivot.matrixWorld);});this.transform.addEventListener('objectChange',()=>this.previewTransform());this.transform.addEventListener('mouseUp',()=>{if(!this.startState)return;this.onCommit(this.transformed());this.startState=null;this.overlay.visible=true;this.dirty=true;});
 this.renderer.domElement.addEventListener('pointerdown',this.pointerDown as EventListener);this.renderer.domElement.addEventListener('pointerup',this.pointerUp as EventListener);this.renderer.domElement.addEventListener('contextmenu',this.noMenu);this.resize=new ResizeObserver(()=>this.resized());this.resize.observe(host);this.animate();}
 noMenu=(e:Event)=>e.preventDefault();
 pointerDown=(e:PointerEvent)=>{this.dragStart=[e.clientX,e.clientY];this.gizmoUsed=!!this.transform.axis;};
 pointerUp=(e:PointerEvent)=>{if(e.button!==0||this.gizmoUsed||Math.hypot(e.clientX-this.dragStart[0],e.clientY-this.dragStart[1])>5||!this.state)return;const rect=this.renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,this.camera);const hits=ray.intersectObjects([...this.meshes.values()],false),hit=hits[0],add=e.shiftKey,s=this.state;if(s.mode==='object'){this.onSelect(hit?(hit.object.userData.modelId as string):null,null,add);return;}const active=s.project.objects.find(o=>o.id===s.selected[0]);if(!active)return;const mesh=this.meshes.get(active.id);if(!mesh)return;if(s.element==='face'){const own=hits.find(h=>h.object===mesh);if(own)this.onSelect(active.id,mesh.geometry.userData.faceMap[own.faceIndex!],add);else if(!add)this.onSelect(active.id,null,false);return;}
 const points=active.mesh.vertices.map(v=>vec(v).applyMatrix4(matrix(active))),screen=points.map(p=>{const v=p.clone().project(this.camera);return new THREE.Vector2((v.x+1)*rect.width/2+rect.left,(-v.y+1)*rect.height/2+rect.top);}),p=new THREE.Vector2(e.clientX,e.clientY);let best=-1,dist=13;const visible=(point:THREE.Vector3)=>{if(s.xray)return true;const projected=point.clone().project(this.camera),test=new THREE.Raycaster();test.setFromCamera(new THREE.Vector2(projected.x,projected.y),this.camera);const surface=test.intersectObjects([...this.meshes.values()],false)[0];return !surface||surface.distance+Math.max(.015,surface.distance*.002)>=point.distanceTo(test.ray.origin);};if(s.element==='vertex')screen.forEach((v,i)=>{const d=v.distanceTo(p);if(d<dist&&visible(points[i])){best=i;dist=d;}});else edges(active.mesh).forEach(([a,b],i)=>{const ab=screen[b].clone().sub(screen[a]),t=THREE.MathUtils.clamp(p.clone().sub(screen[a]).dot(ab)/Math.max(ab.lengthSq(),.001),0,1),d=screen[a].clone().addScaledVector(ab,t).distanceTo(p);if(d<dist&&visible(points[a].clone().lerp(points[b],t))){best=i;dist=d;}});this.onSelect(active.id,best>=0?best:null,add);};
 resized(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);if(this.camera instanceof THREE.PerspectiveCamera)this.camera.aspect=w/h;else{const span=(this.camera.top-this.camera.bottom)/2;this.camera.left=-span*w/h;this.camera.right=span*w/h;}this.camera.updateProjectionMatrix();this.dirty=true;}
 animate=()=>{this.frameId=requestAnimationFrame(this.animate);this.controls.update();if(this.dirty||!this.software){this.renderer.render(this.scene,this.camera);this.dirty=false;}};
 clear(g:THREE.Group){g.children.forEach(n=>n.traverse(child=>{const c=child as THREE.Mesh;if(c.geometry)c.geometry.dispose();if(c.material)(Array.isArray(c.material)?c.material:[c.material]).forEach(m=>m.dispose());}));g.clear();}
 material(o:ModelObject){const d=o.material,s=this.state!,mat=new THREE.MeshStandardMaterial({color:s.shading==='solid'?'#a0a1a4':d.color,metalness:s.shading==='solid'?0:d.metalness,roughness:s.shading==='solid'?.75:d.roughness,emissive:d.emissive,opacity:s.xray?.38:d.opacity,transparent:s.xray||d.opacity<1,wireframe:s.shading==='wireframe',side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:1});if(s.shading==='material')for(const [key,prop] of [['texture','map'],['normalMap','normalMap'],['roughnessMap','roughnessMap']] as const){const url=key==='texture'&&d.checker?'checker':d[key];if(!url)continue;const cacheKey=url+'|'+d.repeat+'|'+key;let t=this.textures.get(cacheKey);if(!t){t=url==='checker'?checkerTexture():new THREE.TextureLoader().load(url,()=>this.dirty=true);if(key==='texture')t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(d.repeat,d.repeat);t.anisotropy=this.renderer instanceof THREE.WebGLRenderer?Math.min(8,this.renderer.capabilities.getMaxAnisotropy()):1;this.textures.set(cacheKey,t);}mat[prop]=t;}return mat;}
 update(s:ViewState){this.state=s;this.dirty=true;this.overlay.visible=true;this.grid.visible=s.grid;this.clear(this.group);this.clear(this.overlay);this.meshes.clear();for(const o of s.project.objects){if(!o.visible)continue;const mesh=new THREE.Mesh(geometry(o.mesh,o.smooth),this.material(o));mesh.name=o.name;mesh.userData.modelId=o.id;mesh.applyMatrix4(matrix(o));mesh.castShadow=true;mesh.receiveShadow=true;this.group.add(mesh);this.meshes.set(o.id,mesh);if(s.selected.includes(o.id)||s.wire){const lines=edges(o.mesh).flatMap(([a,b])=>[...o.mesh.vertices[a],...o.mesh.vertices[b]]),geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));const line=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:s.selected.includes(o.id)?0xd9b363:0x696c73,opacity:s.mode==='edit'?.45:.72,transparent:true,depthTest:!s.xray}));line.applyMatrix4(matrix(o));this.overlay.add(line);}}
 const active=s.project.objects.find(o=>o.id===s.selected[0]);if(s.mode==='edit'&&active?.visible){const m=active.mesh,t=matrix(active),ids=new Set(selectedVertices(m,s.element,s.selection));if(s.element==='vertex')for(const selected of [false,true]){const pts=m.vertices.flatMap((v,i)=>(ids.has(i)===selected)?[...v]:[]),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));const p=new THREE.Points(g,new THREE.PointsMaterial({color:selected?0xffca67:0xa0a0a4,size:this.software?(selected?.025:.016):(selected?8:5),sizeAttenuation:false,depthTest:!s.xray}));p.applyMatrix4(t);this.overlay.add(p);}if(s.element==='edge'){const es=edges(m),lines=s.selection.flatMap(i=>es[i]?[...m.vertices[es[i][0]],...m.vertices[es[i][1]]]:[]),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));const p=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0xffc86b,depthTest:!s.xray}));p.applyMatrix4(t);this.overlay.add(p);}if(s.element==='face'&&s.selection.length){const sub={...m,faces:s.selection.map(i=>m.faces[i]).filter(Boolean),uvs:s.selection.map(i=>m.uvs[i]).filter(Boolean)},p=new THREE.Mesh(geometry(sub),new THREE.MeshBasicMaterial({color:0xe6b652,opacity:.3,transparent:true,side:THREE.DoubleSide,depthTest:!s.xray,depthWrite:false}));p.applyMatrix4(t);this.overlay.add(p);}}
 this.transform.detach();if(s.tool!=='select'&&active?.visible){let points:THREE.Vector3[]=[];if(s.mode==='edit')points=selectedVertices(active.mesh,s.element,s.selection).map(i=>vec(active.mesh.vertices[i]).applyMatrix4(matrix(active)));else points=s.project.objects.filter(o=>s.selected.includes(o.id)&&o.visible).map(o=>vec(o.position));if(points.length){this.pivot.position.copy(points.reduce((a,b)=>a.add(b),new THREE.Vector3()).divideScalar(points.length));this.pivot.rotation.set(0,0,0);this.pivot.scale.set(1,1,1);if(s.space==='local'&&s.selected.length===1)this.pivot.rotation.set(...active.rotation.map(n=>THREE.MathUtils.degToRad(n)) as V3);this.pivot.updateMatrixWorld();this.transform.setMode(s.tool);this.transform.setSpace(s.space);this.transform.setTranslationSnap(s.snap?.25:null);this.transform.setRotationSnap(s.snap?Math.PI/12:null);this.transform.setScaleSnap(s.snap?.1:null);this.transform.attach(this.pivot);}}
 }
 transformed(){const s=this.startState;if(!s)return [];this.pivot.updateMatrixWorld();const delta=this.pivot.matrixWorld.clone().multiply(this.startMatrix.clone().invert());return s.project.objects.filter(o=>s.selected.includes(o.id)).map(source=>{const o=clone(source);if(s.mode==='edit'){const local=matrix(o).invert().multiply(delta).multiply(matrix(o)),ids=new Set(selectedVertices(o.mesh,s.element,s.selection));o.mesh.vertices=o.mesh.vertices.map((v,i)=>ids.has(i)?arr(vec(v).applyMatrix4(local)):v);}else{const pos=new THREE.Vector3(),q=new THREE.Quaternion(),scale=new THREE.Vector3();delta.clone().multiply(matrix(o)).decompose(pos,q,scale);o.position=arr(pos);const e=new THREE.Euler().setFromQuaternion(q);o.rotation=[e.x,e.y,e.z].map(THREE.MathUtils.radToDeg) as V3;o.scale=arr(scale);}return o;});}
 previewTransform(){if(!this.startState)return;for(const o of this.transformed()){const mesh=this.meshes.get(o.id);if(!mesh)continue;if(this.startState.mode==='edit'){mesh.geometry.dispose();mesh.geometry=geometry(o.mesh,o.smooth);}else{mesh.position.copy(vec(o.position));mesh.rotation.set(...o.rotation.map(THREE.MathUtils.degToRad) as V3);mesh.scale.copy(vec(o.scale));}}this.overlay.visible=false;this.dirty=true;}
 view(kind:string){this.overlay.visible=true;const target=this.controls.target,d=this.camera.position.distanceTo(target),direction=kind==='front'?new THREE.Vector3(0,0,1):kind==='back'?new THREE.Vector3(0,0,-1):kind==='top'?new THREE.Vector3(0,1,.0001):kind==='right'?new THREE.Vector3(1,0,0):kind==='left'?new THREE.Vector3(-1,0,0):new THREE.Vector3(1,.72,1).normalize();this.camera.position.copy(target).addScaledVector(direction,d);this.camera.up.set(0,1,0);this.controls.update();this.onView(kind==='perspective'?'User perspective':kind[0].toUpperCase()+kind.slice(1)+' view');this.dirty=true;}
 toggleProjection(){const old=this.camera,w=this.host.clientWidth,h=this.host.clientHeight,d=old.position.distanceTo(this.controls.target);if(old instanceof THREE.PerspectiveCamera){const span=d*Math.tan(THREE.MathUtils.degToRad(20));this.camera=new THREE.OrthographicCamera(-span*w/h,span*w/h,span,-span,.01,1000);}else this.camera=new THREE.PerspectiveCamera(40,w/h,.01,1000);this.camera.position.copy(old.position);this.camera.quaternion.copy(old.quaternion);this.controls.object=this.camera;this.transform.camera=this.camera;this.camera.updateProjectionMatrix();this.controls.update();this.onView(this.camera instanceof THREE.OrthographicCamera?'Orthographic':'User perspective');this.dirty=true;}
 frame(all=false){if(!this.state)return;const objs=this.state.project.objects.filter(o=>o.visible&&(all||this.state!.selected.includes(o.id))),box=new THREE.Box3();objs.forEach(o=>o.mesh.vertices.forEach(v=>box.expandByPoint(vec(v).applyMatrix4(matrix(o)))));if(box.isEmpty())return;const c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length(),dir=this.camera.position.clone().sub(this.controls.target).normalize();this.controls.target.copy(c);this.camera.position.copy(c).addScaledVector(dir,Math.max(size*1.6,1));if(this.camera instanceof THREE.OrthographicCamera){const aspect=this.host.clientWidth/this.host.clientHeight;this.camera.top=size*.7;this.camera.bottom=-size*.7;this.camera.left=-size*.7*aspect;this.camera.right=size*.7*aspect;this.camera.zoom=1;this.camera.updateProjectionMatrix();}this.controls.update();this.dirty=true;}
 screenshot(){this.renderer.render(this.scene,this.camera);return this.renderer instanceof THREE.WebGLRenderer?this.renderer.domElement.toDataURL('image/png'):'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(this.renderer.domElement));}
 dispose(){cancelAnimationFrame(this.frameId);this.resize.disconnect();this.controls.dispose();this.transform.dispose();this.renderer.domElement.removeEventListener('pointerdown',this.pointerDown as EventListener);this.renderer.domElement.removeEventListener('pointerup',this.pointerUp as EventListener);this.clear(this.group);this.clear(this.overlay);this.textures.forEach(t=>t.dispose());this.scene.environment?.dispose();if(this.renderer instanceof THREE.WebGLRenderer)this.renderer.dispose();this.renderer.domElement.remove();}
}
